### ISSUE TITLE
"message":"Address not found in wallet"

### ISSUE THREAD

**Issue by miltosc** [Overtorment/Cashier-BTC#27]
Hello!

I get the following error when i run nodejs worker.js although npm test works

(node:13420) UnhandledPromiseRejectionWarning: Error: {"result":null,"error":{"code":-4,"message":"Address not found in wallet"},"id":"ca143925-f031-42eb-b559-d36c8a6c08ce"}

    at IncomingMessage.<anonymous> (/home/Desktop/Cashier-BTC/node_modules/jayson/lib/client/http.js:74:21)
    at IncomingMessage.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1103:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
(node:13420) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:13420) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

What should i do ? 
Thank you in advance

**Comment by miltosc** [comment]
npm test created data in the couchdb . I deleted the db and recreated empty without running npm test and everything works now
